import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ZebecPlayer from "../components/zebecplayer";
import {useState} from "react";
import {ConnectWallet, StartStream} from "../components/phantom";

const Home: NextPage = () => {
  const [sender, setSender] = useState('11111111111111111111111111111111111111111111')
  const [pda, setPda] = useState('11111111111111111111111111111111111111111111')
  const receiver = '37AURP6wbtNexNWsds7EXWSpQGv5mU8EHcUM3fVCVoh6'
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <ZebecPlayer
              url="http://localhost:5000/stream"
              sender={sender}
              pda={pda}
          />
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <ConnectWallet setSender={setSender}/>
          </a>

          <a className={styles.card}>
            <StartStream sender={sender} receiver={receiver} setPda={setPda}/>
            {pda}
          </a>

          <a className={styles.card}>
            <h2>Public Key &rarr;</h2>
            <p>{sender}</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
